// src/client/About.tsx

import { useState } from 'preact/hooks'
import { render } from 'preact'
//import { App } from './About/app.tsx'
import Head from '../components/Head';
import Footer from '../components/Footer';
//
export function App() {
  const [count, setCount] = useState(0)

  return (
  <>
    <div class="main_body_wrap container mx-auto my-2 px-8 bg-white">
      <Head />
      <div>
      </div>
      <h1 class="text-4xl font-bold">About!!!</h1>
      <hr />
      <div class="card">
        <button onClick={() => setCount((count) => count + 1)}>
          [ count ]  is {count}
        </button>
      </div>
      <hr />
    </div>
    <Footer />
  </>
  )
}

render(<App />, document.getElementById('app')!);

// src/client/About.svelte
<script lang="ts">
console.log("#about");
import Head from '../components/Head.svelte';
</script>

<!-- -->
<main>
  <div class="container mx-auto my-2 px-8 bg-white">
    <Head />
    <hr />
    <h1 class="text-4xl font-bold">About</h1>
  </div>
</main>

<style>
</style>
<!--
<a href="/">[ home ]</a>
-->
